# ===================================================================
#                      実験設定ファイル
# ===================================================================

# --- 1. 全体設定 ---
# 再現性を担保するための乱数シード
seed: 42
# 結果を出力するファイルパス
results_file: "results/experiment_outputs.yaml"
# 使用するデバイス ('cuda' or 'cpu')
# GPUが利用可能な場合は 'cuda' に変更
device: "cuda"

save_models: false
model_save_dir: "models/" # 保存先のディレクトリ名

# --- 2. 実験範囲の設定 ---
# 対象とする数字のペア。nullにすると全45ペアで実行
# 最初は動作確認のために、少数のペアに絞ることを推奨
# 例: [ [0, 1], [3, 8], [4, 9] ]
# target_pairs: [ [0, 1], [3, 8] ] # 似ていないペアと似ているペアの例
target_pairs: null # 全ペアで実行する場合はこちらを有効化

# 試行する誤りデータの種類
error_types:
  - "mutual_mixing"
  - "external_noise"

# 試行する誤りデータの割合 (%の少数表記)
error_rates:
  - 0.0
  - 0.05
  - 0.10
  - 0.15
  - 0.20
  - 0.25
  - 0.30
  - 0.35
  - 0.40
  - 0.45
  - 0.50
  - 0.55
  - 0.60
  - 0.65
  - 0.70
  - 0.75
  - 0.80
  - 0.85
  - 0.90
  - 0.95
  - 1.0


# --- 3. モデルのハイパーパラメータ ---
model_params:
  input_size: 784    # 28x28ピクセル
  # 隠れ層のユニット数 (3層)
  hidden_layers: [1024, 512, 256]
  output_size: 1       # 二値分類
  dropout_rate: 0.4    # ドロップアウト率


# --- 4. 学習のハイパーパラメータ ---
training_params:
  learning_rate: 0.001
  epochs: 50           # 最大エポック数
  batch_size: 2048
  # 学習データから検証データとして切り出す割合
  validation_split: 0.2
  num_workers: 8 #スレッド数